In [29]:
import numpy as np
import pandas as pd
import matplotlib as plt
import seaborn as sns

In [30]:
df=pd.read_csv(r"C:\Users\ugand\Desktop\Data Science\car_evaluation.csv")

In [31]:
df

      vhigh vhigh.1      2   2.1  small   low  unacc
0     vhigh   vhigh      2     2  small   med  unacc
1     vhigh   vhigh      2     2  small  high  unacc
2     vhigh   vhigh      2     2    med   low  unacc
3     vhigh   vhigh      2     2    med   med  unacc
4     vhigh   vhigh      2     2    med  high  unacc
...     ...     ...    ...   ...    ...   ...    ...
1722    low     low  5more  more    med   med   good
1723    low     low  5more  more    med  high  vgood
1724    low     low  5more  more    big   low  unacc
1725    low     low  5more  more    big   med   good
1726    low     low  5more  more    big  high  vgood

[1727 rows x 7 columns]

In [32]:
col_names = ["buying", "engine","doors", "persons", "boot_space", "safty", "class" ]
df.columns = col_names
df

     buying engine  doors persons boot_space safty  class
0     vhigh  vhigh      2       2      small   med  unacc
1     vhigh  vhigh      2       2      small  high  unacc
2     vhigh  vhigh      2       2        med   low  unacc
3     vhigh  vhigh      2       2        med   med  unacc
4     vhigh  vhigh      2       2        med  high  unacc
...     ...    ...    ...     ...        ...   ...    ...
1722    low    low  5more    more        med   med   good
1723    low    low  5more    more        med  high  vgood
1724    low    low  5more    more        big   low  unacc
1725    low    low  5more    more        big   med   good
1726    low    low  5more    more        big  high  vgood

[1727 rows x 7 columns]

In [33]:
x=df.drop(['class'],axis=1)
y=df['class']

In [34]:
from sklearn.preprocessing import OrdinalEncoder

In [35]:
enc = OrdinalEncoder()
enc.fit(df[['buying', 'engine','doors', 'persons', 'boot_space', 'safty']])

OrdinalEncoder()

In [36]:
ds=enc.transform(df[['buying', 'engine','doors', 'persons', 'boot_space', 'safty']])

In [37]:
ab=pd.DataFrame(ds,columns =df.columns[:-1])
ab.head()

   buying  engine  doors  persons  boot_space  safty
0     3.0     3.0    0.0      0.0         2.0    2.0
1     3.0     3.0    0.0      0.0         2.0    0.0
2     3.0     3.0    0.0      0.0         1.0    1.0
3     3.0     3.0    0.0      0.0         1.0    2.0
4     3.0     3.0    0.0      0.0         1.0    0.0